version: "3.8"

name: "hermes-local"

services:
  postgres:
    image: 'postgres:latest'
    restart: on-failure
    shm_size: '1gb' # needed to allow vacuum
    env_file:
      - env/${ENVIRONMENT}/.env_hermes.properties
    volumes:
      - "hermes_postgres:/var/lib/postgresql/data"
    ports:
      - "127.0.0.1:22642:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d hermes -U hermes"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  hermes_postgres:
    driver: local
